services:
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    env_file:
      - backend/.env
    ports:
      - "8000:8000"

  worker:
    build:
      context: .
      dockerfile: worker.Dockerfile
    env_file:
      - backend/.env

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    env_file:
      - frontend/.env
    ports:
      - "3000:3000"
    depends_on:
      - backend
