export const ErrorCodes = {
  NO_TOKEN: "NO_TOKEN",
  REFRESH_FAILED: "REFRESH_FAILED",
  AUTH_FAILED: "AUTH_FAILED",
  NOT_AUTHENTICATED: "NOT_AUTHENTICATED",
  SERVER_ERROR: "SERVER_ERROR",
  BOOKMARK_NOT_FOUND: "BOOKMARK_NOT_FOUND",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  URL_NOT_SCRAPABLE: "URL_NOT_SCRAPABLE",
  BOOKMARK_ALREADY_EXISTS: "BOOKMARK_ALREADY_EXISTS",
  INVALID_SEARCH_TYPE: "INVALID_SEARCH_TYPE",
  JOB_IS_ALREADY_COMPLETED: "JOB_IS_ALREADY_COMPLETED",
  JOB_NOT_FOUND: "JOB_NOT_FOUND",
} as const;

